# Generated by Django 5.2.3 on 2025-06-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
