# Generated by Django 5.2.3 on 2025-07-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='offers/')),
                ('link', models.URLField(default='/product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
