# Generated by Django 5.2.3 on 2025-07-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='link',
        ),
    ]
