# Generated by Django 5.2.3 on 2025-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_remove_offer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('color', models.TextField()),
                ('size', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
