# Generated by Django 5.2.3 on 2025-07-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_size', models.CharField(blank=True, max_length=50)),
                ('selected_color', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.product')),
            ],
        ),
    ]
