# Generated by Django 5.2.3 on 2025-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0009_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
